/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {

  docsbars: [

    {
      type: 'category',
      label: 'Introduction',
      items: ['cbdb-overview','cbdb-architecture','cbdb-scenarios','cbdb-vs-gp-features','cbdb-glossary']
     },

    {
      type: 'category',
      label: 'Deployment Guides',
      items: ['cbdb-op-software-hardware',
      {
        type: 'category',
        label: 'Physical Machine Deployment',
        items: ['cbdb-op-deploy-arch','cbdb-op-deploy-guide']
      }]
    },

    {
      type: 'category',
      label: 'Prepare Database',
      items: ['start-and-stop-cbdb-database','create-and-manage-database','connect-to-cbdb']
     },

    'import-data-into-cbdb',

    {
      type: 'category',
      label: 'DB Operations',
      items: ['basic-db-operations','create-and-manage-tables','insert-update-delete-row-data']
     },

    {
      type: 'category',
      label: 'System Admin Guides',
      items: ['start-and-stop-cbdb-database','backup-and-restore-cbdb','manage-roles-and-permissions','update-stats-using-analyze','cbdb-query-performance']
    },

    {
      type: 'category',
      label: 'Reference Guides',
      items: [
        {
          type: 'category',
          label: 'SQL Statements',
          items: [
            'sql-stmts/sql-stmt-create-view',
            'sql-stmts/sql-stmt-create-function',
            'sql-stmts/sql-stmt-reindex',
            'sql-stmts/sql-stmt-alter-foreign-data-wrapper',
            'sql-stmts/sql-stmt-create-rule',
            'sql-stmts/sql-stmt-set-role',
            'sql-stmts/sql-stmt-drop-role',
            'sql-stmts/sql-stmt-alter-domain',
            'sql-stmts/sql-stmt-drop-type',
            'sql-stmts/sql-stmt-create-operator-class',
            'sql-stmts/sql-stmt-create-foreign-data-wrapper',
            'sql-stmts/sql-stmt-alter-foreign-table',
            'sql-stmts/sql-stmt-alter-tablespace',
            'sql-stmts/sql-stmt-drop-access-method',
            'sql-stmts/sql-stmt-revoke',
            'sql-stmts/sql-stmt-drop-extension',
            'sql-stmts/sql-stmt-alter-conversion',
            'sql-stmts/sql-stmt-create-transform',
            'sql-stmts/sql-stmt-alter-function',
            'sql-stmts/sql-stmt-alter-external-table',
            'sql-stmts/sql-stmt-select-into',
            'sql-stmts/sql-stmt-release-savepoint',
            'sql-stmts/sql-stmt-create-extension',
            'sql-stmts/sql-stmt-grant',
            'sql-stmts/sql-stmt-drop-transform',
            'sql-stmts/sql-stmt-analyze',
            'sql-stmts/sql-stmt-create-table',
            'sql-stmts/sql-stmt-drop-index',
            'sql-stmts/sql-stmt-prepare',
            'sql-stmts/sql-stmt-drop-text-search-template',
            'sql-stmts/sql-stmt-drop-owned',
            'sql-stmts/sql-stmt-show',
            'sql-stmts/sql-stmt-alter-index',
            'sql-stmts/sql-stmt-alter-server',
            'sql-stmts/sql-stmt-set-constraints',
            'sql-stmts/sql-stmt-drop-resource-group',
            'sql-stmts/sql-stmt-alter-resource-queue',
            'sql-stmts/sql-stmt-drop-function',
            'sql-stmts/sql-stmt-alter-materialized-view',
            'sql-stmts/sql-stmt-insert',
            'sql-stmts/sql-stmt-explain',
            'sql-stmts/sql-stmt-alter-policy',
            'sql-stmts/sql-stmt-cluster',
            'sql-stmts/sql-stmt-alter-text-search-parser',
            'sql-stmts/sql-stmt-start-transaction',
            'sql-stmts/sql-stmt-create-resource-queue',
            'sql-stmts/sql-stmt-listen',
            'sql-stmts/sql-stmt-create-text-search-configuration',
            'sql-stmts/sql-stmt-create-schema',
            'sql-stmts/sql-stmt-copy',
            'sql-stmts/sql-stmt-alter-text-search-dictionary',
            'sql-stmts/sql-stmt-create-tablespace',
            'sql-stmts/sql-stmt-alter-routine',
            'sql-stmts/sql-stmt-drop-text-search-dictionary',
            'sql-stmts/sql-stmt-declare',
            'sql-stmts/sql-stmt-drop-text-search-parser',
            'sql-stmts/sql-stmt-create-group',
            'sql-stmts/sql-stmt-create-table-as',
            'sql-stmts/sql-stmt-set',
            'sql-stmts/sql-stmt-create-language',
            'sql-stmts/sql-stmt-drop-trigger',
            'sql-stmts/sql-stmt-create-external-table',
            'sql-stmts/sql-stmt-select',
            'sql-stmts/sql-stmt-discard',
            'sql-stmts/sql-stmt-create-access-method',
            'sql-stmts/sql-stmt-import-foreign-schema',
            'sql-stmts/sql-stmt-set-session-authorization',
            'sql-stmts/sql-stmt-alter-operator-class',
            'sql-stmts/sql-stmt-reassign-owned',
            'sql-stmts/sql-stmt-drop-language',
            'sql-stmts/sql-stmt-do',
            'sql-stmts/sql-stmt-drop-statistics',
            'sql-stmts/sql-stmt-create-operator-family',
            'sql-stmts/sql-stmt-retrieve',
            'sql-stmts/sql-stmt-create-conversion',
            'sql-stmts/sql-stmt-deallocate',
            'sql-stmts/sql-stmt-alter-extension',
            'sql-stmts/sql-stmt-alter-rule',
            'sql-stmts/sql-stmt-drop-cast',
            'sql-stmts/sql-stmt-drop-materialized-view',
            'sql-stmts/sql-stmt-drop-user',
            'sql-stmts/sql-stmt-alter-user-mapping',
            'sql-stmts/sql-stmt-alter-language',
            'sql-stmts/sql-stmt-drop-schema',
            'sql-stmts/sql-stmt-alter-default-privileges',
            'sql-stmts/sql-stmt-alter-view',
            'sql-stmts/sql-stmt-drop-text-search-configuration',
            'sql-stmts/sql-stmt-alter-operator-family',
            'sql-stmts/sql-stmt-create-cast',
            'sql-stmts/sql-stmt-begin',
            'sql-stmts/sql-stmt-drop-sequence',
            'sql-stmts/sql-stmt-create-domain',
            'sql-stmts/sql-stmt-alter-protocol',
            'sql-stmts/sql-stmt-create-user',
            'sql-stmts/sql-stmt-alter-database',
            'sql-stmts/sql-stmt-drop-foreign-data-wrapper',
            'sql-stmts/sql-stmt-alter-resource-group',
            'sql-stmts/sql-stmt-create-foreign-table',
            'sql-stmts/sql-stmt-drop-resource-queue',
            'sql-stmts/sql-stmt-execute',
            'sql-stmts/sql-stmt-lock',
            'sql-stmts/sql-stmt-close',
            'sql-stmts/sql-stmt-create-operator',
            'sql-stmts/sql-stmt-update',
            'sql-stmts/sql-stmt-move',
            'sql-stmts/sql-stmt-drop-aggregate',
            'sql-stmts/sql-stmt-drop-external-table',
            'sql-stmts/sql-stmt-delete',
            'sql-stmts/sql-stmt-savepoint',
            'sql-stmts/sql-stmt-create-aggregate',
            'sql-stmts/sql-stmt-create-user-mapping',
            'sql-stmts/sql-stmt-alter-type',
            'sql-stmts/sql-stmt-drop-server',
            'sql-stmts/sql-stmt-checkpoint',
            'sql-stmts/sql-stmt-alter-sequence',
            'sql-stmts/sql-stmt-alter-role',
            'sql-stmts/sql-stmt-drop-database',
            'sql-stmts/sql-stmt-drop-protocol',
            'sql-stmts/sql-stmt-create-text-search-dictionary',
            'sql-stmts/sql-stmt-create-database',
            'sql-stmts/sql-stmt-create-protocol',
            'sql-stmts/sql-stmt-fetch',
            'sql-stmts/sql-stmt-create-text-search-template',
            'sql-stmts/sql-stmt-alter-procedure',
            'sql-stmts/sql-stmt-drop-group',
            'sql-stmts/sql-stmt-create-server',
            'sql-stmts/sql-stmt-drop-operator-family',
            'sql-stmts/sql-stmt-drop-operator',
            'sql-stmts/sql-stmt-rollback',
            'sql-stmts/sql-stmt-drop-user-mapping',
            'sql-stmts/sql-stmt-alter-text-search-template',
            'sql-stmts/sql-stmt-drop-domain',
            'sql-stmts/sql-stmt-alter-group',
            'sql-stmts/sql-stmt-values',
            'sql-stmts/sql-stmt-set-transaction',
            'sql-stmts/sql-stmt-alter-operator',
            'sql-stmts/sql-stmt-alter-statistics',
            'sql-stmts/sql-stmt-refresh-materialized-view',
            'sql-stmts/sql-stmt-create-sequence',
            'sql-stmts/sql-stmt-alter-collation',
            'sql-stmts/sql-stmt-create-text-search-parser',
            'sql-stmts/sql-stmt-alter-aggregate',
            'sql-stmts/sql-stmt-drop-tablespace',
            'sql-stmts/sql-stmt-alter-table',
            'sql-stmts/sql-stmt-drop-foreign-table',
            'sql-stmts/sql-stmt-create-trigger',
            'sql-stmts/sql-stmt-drop-routine',
            'sql-stmts/sql-stmt-truncate',
            'sql-stmts/sql-stmt-drop-operator-class',
            'sql-stmts/sql-stmt-create-materialized-view',
            'sql-stmts/sql-stmt-create-policy',
            'sql-stmts/sql-stmt-create-index',
            'sql-stmts/sql-stmt-drop-table',
            'sql-stmts/sql-stmt-alter-schema',
            'sql-stmts/sql-stmt-alter-trigger',
            'sql-stmts/sql-stmt-unlisten',
            'sql-stmts/sql-stmt-create-role',
            'sql-stmts/sql-stmt-vacuum',
            'sql-stmts/sql-stmt-drop-policy',
            'sql-stmts/sql-stmt-create-type',
            'sql-stmts/sql-stmt-rollback-to-savepoint',
            'sql-stmts/sql-stmt-create-collation',
            'sql-stmts/sql-stmt-end',
            'sql-stmts/sql-stmt-drop-collation',
            'sql-stmts/sql-stmt-create-procedure',
            'sql-stmts/sql-stmt-create-resource-group',
            'sql-stmts/sql-stmt-drop-view',
            'sql-stmts/sql-stmt-call',
            'sql-stmts/sql-stmt-load',
            'sql-stmts/sql-stmt-commit',
            'sql-stmts/sql-stmt-create-statistics',
            'sql-stmts/sql-stmt-drop-procedure',
            'sql-stmts/sql-stmt-reset',
            'sql-stmts/sql-stmt-alter-user',
            'sql-stmts/sql-stmt-alter-text-search-configuration',
            'sql-stmts/sql-stmt-drop-conversion',
            'sql-stmts/sql-stmt-comment',
            'sql-stmts/sql-stmt-drop-rule',
            'sql-stmts/sql-stmt-notify',
            'sql-stmts/sql-stmt-abort',
          ]
         },
        {
          type: 'category',
          label: 'Database Utilities',
          items: [
            'db-utilities/db-util-pg-restore',
            'db-utilities/db-util-gpcopy',
            'db-utilities/db-util-gpsupport',
            'db-utilities/db-util-gprecoverseg',
            'db-utilities/db-util-pg-checksums',
            'db-utilities/db-util-dropdb',
            'db-utilities/db-util-gpmemreport',
            'db-utilities/db-util-gpinitsystem',
            'db-utilities/db-util-gpsupport-analyze-session',
            'db-utilities/db-util-gpstop',
            'db-utilities/db-util-psql',
            'db-utilities/db-util-gpfdist',
            'db-utilities/db-util-gpstate',
            'db-utilities/db-util-gpmovemirrors',
            'db-utilities/db-util-pg-dump',
            'db-utilities/db-util-createdb',
            'db-utilities/db-util-vacuumdb',
            'db-utilities/db-util-gpsync',
            'db-utilities/db-util-analyzedb',
            'db-utilities/db-util-gpexpand',
            'db-utilities/db-util-gpcheckcat',
            'db-utilities/db-util-gpaddmirrors',
            'db-utilities/db-util-createuser',
            'db-utilities/db-util-gpinitstandby',
            'db-utilities/db-util-gpcheckperf',
            'db-utilities/db-util-gpssh',
            'db-utilities/db-util-gpsupport-gp-log-collector',
            'db-utilities/db-util-clusterdb',
            'db-utilities/db-util-gpconfig',
            'db-utilities/db-util-gpload',
            'db-utilities/db-util-pg-dumpall',
            'db-utilities/db-util-dropuser',
            'db-utilities/db-util-gpmemwatcher',
            'db-utilities/db-util-gplogfilter',
            'db-utilities/db-util-gpreload',
            'db-utilities/db-util-reindexdb',
            'db-utilities/db-util-plcontainer-configuration',
            'db-utilities/db-util-gpssh-exkeys',
            'db-utilities/db-util-pg-config',
            'db-utilities/db-util-plcontainer',
            'db-utilities/db-util-gpsupport-gp-storage-rca-collector',
            'db-utilities/db-util-gppkg',
            'db-utilities/db-util-gpstart',
            'db-utilities/db-util-gpactivatestandby',
            'db-utilities/db-util-gpsupport-gpstatscheck',
            'db-utilities/db-util-gpdeletesystem',
            'db-utilities/db-util-gpsupport-packcore',
          ]
         },
         {
          type: 'category',
          label: 'SQL Functions',
          items: [
            'ref-function-summary',
            'ref-advanced-aggregate-functions',
            'ref-json-functions-and-operators',
            'ref-range-functions-and-operators',
            'ref-text-search-functions-and-operators',
            'ref-window-functions'
          ]
         },
      ]
    },

  ]
}

module.exports = sidebars;
